version: "3.9"
services: 
  # Frontend
  todo-app:
    build: ./frontend
    ports: 
      - 80:80
    networks:
      todo-app-network:
        ipv4_address: 10.88.0.21
  #Database
  pocketbase:
    build: ./pocketbase
    ports:
      - 8085:8085
    networks:
      todo-app-network:
        ipv4_address: 10.88.0.22
  actuator-service:
    build: ./actuator-service
    ports:
      - 8006:8006
    networks:
      todo-app-network:
        ipv4_address: 10.88.0.23
  door-service:
    build: ./door-service
    ports:
      - 8003:8003
    networks:
      todo-app-network:
        ipv4_address: 10.88.0.24
  heat-pump-service:
    build: ./heatPump-service
    ports:
      - 8004:8004
    networks:
      todo-app-network:
        ipv4_address: 10.88.0.25
  weather-service:
    build: ./weather-service-master
    ports:
      - 8002:8002
    networks:
      todo-app-network:
        ipv4_address: 10.88.0.26
  thermometer-service:
    build: ./thermometer-service
    ports:
      - 8005:8005
    networks:
      todo-app-network:
        ipv4_address: 10.88.0.27
  window-service:
    build: ./window-service
    ports:
      - 8001:8001
    networks:
      todo-app-network:
        ipv4_address: 10.88.0.28
  # Backend
  todo-server:
    build: ./backend
    depends_on:
      - pocketbase
    ports: 
      - 8000:8000
    networks:
      todo-app-network:
        #bind to apache proxy pass
        ipv4_address: 10.88.0.11

networks:
  todo-app-network:    
      name: todo-app-network
      driver: bridge
      ipam:
        config:
          - subnet: "10.88.0.0/24"
