version: "3.9"
services: 
  # Frontend
  app:
    build: ./frontend
    ports: 
      - 8080:80
    networks:
      app-network:
        ipv4_address: 10.88.0.21
  #Database
  pocketbase:
    build: ./pocketbase
    ports:
      - 8085:8085
    networks:
      app-network:
        ipv4_address: 10.88.0.22
  door-service:
    build: ./door-service
    ports:
      - 8003:8003
    environment:
      - TTL=110
    networks:
      app-network:
        ipv4_address: 10.88.0.24
  heat-pump-service:
    build: ./heatPump-service
    ports:
      - 8004:8004
    environment:
      - TTL=150
    networks:
      app-network:
        ipv4_address: 10.88.0.25
  weather-service:
    build: ./weather-service-master
    ports:
      - 8002:8002
    environment:
      - TTL=90
    networks:
      app-network:
        ipv4_address: 10.88.0.26
  thermometer-service:
    build: ./thermometer-service
    ports:
      - 8005:8005
    environment:
      - TTL=80
    networks:
      app-network:
        ipv4_address: 10.88.0.27
  window-service-first:
    build: ./window-service
    ports:
      - 8001:8001
    environment:
      - TTL=120
    networks:
      app-network:
        ipv4_address: 10.88.0.28
  window-service-second:
    build: ./window-service
    ports:
      - 8009:8009
    environment:
      - IFACE=10.88.0.29
      - PORT=8009
      - ERROR_PROB = 0
      - DELAY_PROB = 0.2
      - FREQ_MS = 2000
      - TTL=3600
    networks:
      app-network:
        ipv4_address: 10.88.0.29
  # Backend
  server:
    build: ./backend
    depends_on:
      pocketbase:
        condition: service_started
    ports: 
      - 8000:8000
    networks:
      app-network:
        #bind to apache proxy pass
        ipv4_address: 10.88.0.11
  actuator-service:
    build: ./actuator-service
    ports:
      - 8006:8006
    environment:
      - POCKETBASE_ADDRESS=http://10.88.0.22:8085
      - IS_DOCKER_INSTANCE=true
    networks:
      app-network:
        ipv4_address: 10.88.0.23
    depends_on:
      pocketbase:
        condition: service_started

networks:
  app-network:
      name: app-network
      driver: bridge
      ipam:
        config:
          - subnet: "10.88.0.0/24"
