version: "3.9"
services: 
  # Frontend
  todo-app:
    build: ./frontend
    ports: 
      - 8080:80
    networks:
      todo-app-network:
        ipv4_address: 10.88.0.21
  #Database
  pocketbase:
    build: ./pocketbase
    ports:
      - 8085:8085
    networks:
      todo-app-network:
        ipv4_address: 10.88.0.22
  actuatorService:
    build: ./actuator-service
    ports:
      - 8006:8006
    networks:
      todo-app-network:
        ipv4_address: 10.88.0.23
  doorService:
    build: ./door-service
    ports:
      - 8003:8003
    networks:
      todo-app-network:
        ipv4_address: 10.88.0.24
  heatPumpService:
    build: ./heatPump-service
    ports:
      - 8004:8004
    networks:
      todo-app-network:
        ipv4_address: 10.88.0.25
  # Backend
  todo-server:
    build: ./backend
    ports: 
      - 8000:8000
    networks:
      todo-app-network:
        #bind to apache proxy pass
        ipv4_address: 10.88.0.11

networks:
  todo-app-network:    
      name: todo-app-network
      driver: bridge
      ipam:
        config:
          - subnet: "10.88.0.0/24"
